[game]
# What resolution the game will run at. If omitted, the resolution of your primary monitor will be used.
# resolution = "1920x1080"

# What refresh rate the game should try to run with. Same as with resolution, this is determined automatically.
# refresh_rate = 240

# Selects the window mode for the game. One of [Fullscreen, Borderless, Windowed]. Borderless by default.
# mode = Borderless

# Field of view in degrees. By default, this is 60 degrees on a 4:3 screen.
# fov = 90

[patches]
# Whether to skip the logo sequence before the main menu.
# skip_intro = true
