# taxipatch configuration
# https://github.com/stashymane/taxipatch

# comments start with the # symbol, and settings are commented out with a ; symbol
# game refuses to start? other issues? just delete or move this file, the patch will re-generate the default config.

[game]
# What resolution the game will run at.
# Must be formatted as [width]x[height]. Defaults to the primary monitor's current resolution.
; resolution = "1920x1080"

# What refresh rate the game should try to run with.
# Defaults to your primary monitor's current refresh rate.
; refresh_rate = 240

# Selects the window mode for the game.
# One of [Fullscreen, Borderless, Windowed]. Borderless by default.
; mode = Borderless

# Which buffering mode to use.
# One of [Double, Triple]. Double by default.
; buffering_mode = Double

# Requested multisampling / MSAA mode.
# One of [Off, X2, X4, X8]. Off by default.
; multisampling = X4

# Horizontal field of view in degrees. The game originally used 60 degrees on a 4:3 screen.
# An FOV is calculated based on your aspect ratio by default.
; fov = 90

[patches]
# Whether to skip the logo sequence before the main menu.
; skip_intro = true
