on:
  push:
    branches:
      - "master"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        target: [ i686-pc-windows-gnu ]
        profile: [ dev ] # release

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc-mingw-w64-i686
        if: matrix.target == 'i686-pc-windows-gnu'

      - uses: actions/checkout@v6

      - uses: moonrepo/setup-rust@v1
        with:
          targets: ${{ matrix.target }}
          inherit-toolchain: true
          cache-extra-identifier: ${{ matrix.os }}-${{ matrix.target }}-${{ matrix.profile }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: cargo build --target ${{ matrix.target }} --profile ${{ matrix.profile }}
      - run: |
          OUT_PATH="target/${{ matrix.target }}/debug"
          mv "$OUT_PATH/taxipatch.dll" "$OUT_PATH/taxipatch.asi"

      - name: Upload debug artifact
        if: matrix.profile != 'release'
        uses: actions/upload-artifact@v7
        with:
          name: taxipatch-debug
          archive: false
          path: |
            target/${{ matrix.target }}/debug/taxipatch.asi

      - name: Upload release artifact
        if: matrix.profile == 'release'
        uses: actions/upload-artifact@v7
        with:
          name: taxipatch-release
          archive: false
          path: |
            target/${{ matrix.target }}/release/taxipatch.asi
